name: Test

on:
  pull_request:
    branches: [ "test" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: maxim-lobanov/setup-xcode@v1.5.1
      with:
        xcode-version: '13.2.1'
    - name: Build and Test
      run: xcodebuild test -scheme AllTests -destination 'platform=iOS Simulator,OS=15.2,name=iPhone 12 Pro Max'