# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches:
    - 'feature/**'
  pull_request:
    branches: [ "dev" ]

jobs:
  build PRCore:
    name: Build and Test PRCore
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: maxim-lobanov/setup-xcode@v1.5.1
      with:
        xcode-version: 'latest'
    - name: Test PRCore
      run: xcodebuild test -scheme PRCore -destination 'platform=iOS Simulator,OS=latest,name=iPhone 11 Pro Max'
  
  build PRDomainModels:
    name: Build and Test PRDomainModels
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: maxim-lobanov/setup-xcode@v1.5.1
      with:
        xcode-version: 'latest'
    - name: Test PRDomainModels
      run: xcodebuild test -scheme PRDomainModels -destination 'platform=iOS Simulator,OS=latest,name=iPhone 11 Pro Max'
