# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  #push:
    #branches:
    #- 'feature/**'
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout the code
    - uses: actions/checkout@v3
    #- name: Build
      #run: swift build -v
    #- name: Run tests
      #run: swift test -v
    - name: Switch to xcode 14.1
      run: sudo xcode-select -s /Applications/Xcode12.0.1.app
    - name: Build and Test
      run: xcodebuild test -scheme PRPersistence -destination 'platform=iOS Simulator,OS=15.2,name=iPhone 12 Pro Max'
