# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches:
    - 'feature/**'
  pull_request:
    branches: [ "dev" ]

jobs:
  #build_PRCore:
  #  name: Build and Test PRCore
  #  runs-on: macos-latest
#
  #  steps:
  #  - uses: actions/checkout@v3
  #  - uses: maxim-lobanov/setup-xcode@v1.5.1
  #    with:
  #      xcode-version: 'latest'
  #  - name: Test PRCore
  #    run: xcodebuild test -scheme PRCore -destination 'platform=iOS Simulator,OS=latest,name=iPhone 11 Pro Max'
  #
  #build_PRDomainModels:
  #  name: Build and Test PRDomainModels
  #  runs-on: macos-latest
#
  #  steps:
  #  - uses: actions/checkout@v3
  #  - uses: maxim-lobanov/setup-xcode@v1.5.1
  #    with:
  #      xcode-version: 'latest'
  #  - name: Test PRDomainModels
  #    run: xcodebuild test -scheme PRDomainModels -destination 'platform=iOS Simulator,OS=latest,name=iPhone 11 Pro Max'
#
  #build_PRPersistence:
  #  name: Build and Test PRPersistence
  #  runs-on: macos-latest
#
  #  steps:
  #  - uses: actions/checkout@v3
  #  - uses: maxim-lobanov/setup-xcode@v1.5.1
  #    with:
  #      xcode-version: 'latest'
  #  - name: Test PRPersistence
  #    run: xcodebuild test -scheme PRPersistence -destination 'platform=iOS Simulator,OS=latest,name=iPhone 11 Pro Max'

  build_PiacereChef:
    name: Build and Test PiacereChef
    runs-on: macOS-12

    steps:
    - uses: actions/checkout@v3
    - uses: maxim-lobanov/setup-xcode@v1.5.1
      with:
        xcode-version: 'latest'
    - name: Run tests
      run: xcodebuild test -scheme AllTests -project PiacereChef.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 13 Pro Max,OS=15.2' | xcpretty && exit ${PIPESTATUS[0]} -v

